### ISSUE TITLE
Ability to disable trusted list (known_hosts)

### ISSUE THREAD

**Issue by randomnoob** [Snawoot/rsp#1]
Hi,
I've just came across the repo as I was searching for a way to implement SOCKS5 dynamic forwarding with asyncssh. The package was awesome to me, but how do I disable known_hosts completely?

Thanks

**Comment by Snawoot** [comment]
Hello,

Thanks!

This step will disable host key verification and allow MITM inside SSH session. But this is doable, I can add command line option to pass `None` as `known_hosts` in SSHClientOptions, effectively disabling host key verification. So, I can easily implement it, if there some use case for it. Do you think it is worth it?

**Comment by Snawoot** [comment]
Merged some improvements related to known hosts handling (via #2) and pushed to pypi (via v0.3.1). Now application handles missing known_hosts file as well as hosts missing in known hosts file and provides user with instructions what has to be done to proceed with normal operation.

I'm closing current issue since no use case has been outlined when disabled host key validation is desirable.
